---
- name: Ensure Python 3 is installed (macOS)
  homebrew:
    name: python@{{ python_version }}
    state: present

- name: Create symlink for python3
  file:
    src: "/opt/homebrew/bin/python{{ python_version }}"
    dest: "{{ local_bin_dir }}/python"
    state: link
  ignore_errors: yes

