---
- name: Ensure Git is installed (Debian/Ubuntu)
  apt:
    name: git
    state: present
  become: yes

- name: Add GitHub CLI repository
  block:
    - name: Add GitHub CLI GPG key
      shell: |
        sudo mkdir -p /etc/apt/keyrings
        wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null
        sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg
      args:
        executable: /bin/bash
        creates: /etc/apt/keyrings/githubcli-archive-keyring.gpg

    - name: Add GitHub CLI repository
      shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
      args:
        executable: /bin/bash
        creates: /etc/apt/sources.list.d/github-cli.list

- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Install GitHub CLI
  apt:
    name: gh
    state: present
  become: yes

